apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pcscf-loss-latency-from
  namespace: default

spec:
  action: delay
  mode: all

  selector:
    labelSelectors:
      app: pcscf

  delay:
    latency: "200ms"

  loss:
    loss: "5"
