apiVersion: v1
kind: Pod
metadata:
  name: robot-runner
  namespace: ims
spec:
  containers:
    - name: robot-runner
      image: robot-runner:latest
      imagePullPolicy: Never
      command: ["sh", "-c"]
      args:
        - |
          echo "Starting Robot..."
          git clone https://github.com/aabid0909/telecom-lab.git /workspace
          pip install robotframework robotframework-requests
          robot /workspace/chaos-testing-lab/robot-chaos/ims_continuous_health.robot
          echo "Robot completed. Keeping container alive..."
          sleep 3600
