apiVersion: v1
kind: Pod
metadata:
  name: robot-runner
  namespace: ims
spec:
  containers:
  - name: robot
    image: python:3.10-slim
    command: ["sh", "-c"]
    args:
      - |
        set -x
        echo "=== Installing system tools ==="
        apt-get update && apt-get install -y git

        echo "=== Installing Robot Framework ==="
        pip install --no-cache-dir robotframework robotframework-requests

        echo "=== Cloning telecom-lab repo ==="
        git clone https://github.com/aabid0909/telecom-lab.git /workspace

        echo "=== Listing chaos-testing-lab ==="
        ls -R /workspace/chaos-testing-lab

        echo "=== Running Robot during chaos ==="
        robot /workspace/chaos-testing-lab/robot-chaos/ims_continuous_health.robot

        echo "=== Robot execution completed ==="
  restartPolicy: Never

